SELECT `tickets`.`user` AS `id`, `users`.`name`, `tickets`.`seat_number` FROM `tickets` INNER JOIN `users` ON `tickets`.`user` = `users`.`id` WHERE `train` = 11 ORDER BY `seat_number` ASC;

SELECT `tickets`.`user` AS `id`, `users`.`name`, count(`tickets`.`user`) AS `trains_count`, format(sum(`trains`.`distance`) * 0.1, 4) AS `total_distance` FROM `tickets` INNER JOIN `users` ON `tickets`.`user` = `users`.`id` INNER JOIN `trains` ON `tickets`.`train` = `trains`.`id` GROUP BY `users`.`id` ORDER BY `total_distance` DESC LIMIT 6;

SELECT `trains`.`id` AS `id`, `types`.`name` AS `type`, `src_station`.`name` AS `src_stn`, `dst_station`.`name` AS `dst_stn`, Timediff(`trains`.`arrival`, `trains`.`departure`) AS `travel_time` FROM `trains` INNER JOIN `types` ON `trains`.`type` = `types`.`id` INNER JOIN `stations` AS `src_station` ON `trains`.`source` = `src_station`.`id` INNER JOIN `stations` AS `dst_station` ON `trains`.`destination` = `dst_station`.`id` ORDER BY `travel_time` DESC LIMIT 6;

SELECT `types`.`name` AS `type`, `src_station`.`name` AS `src_stn`, `dst_station`.`name` AS `dst_stn`, `trains`.`departure` AS `departure`, `trains`.`arrival` AS `arrival`, round((`types`.`fare_rate` * 0.01 * `trains`.`distance` * 0.1), -2) AS `fare` FROM `trains` INNER JOIN `types` ON `types`.`id` = `trains`.`type` INNER JOIN `stations` AS `src_station` ON `trains`.`source` = `src_station`.`id` INNER JOIN `stations` AS `dst_station` ON `trains`.`destination` = `dst_station`.`id` ORDER BY `trains`.`departure` ASC;

SELECT `trains`.`id` AS `id`, `types`.`name` AS `type`, `src_station`.`name` AS `src_stn`, `dst_station`.`name` AS `dst_stn`, count(`tickets`.`train`) AS `occupied`, `types`.`max_seats` AS `maximum` FROM `trains` INNER JOIN `types` ON `trains`.`type` = `types`.`id` INNER JOIN `stations` AS `src_station` ON `trains`.`source` = `src_station`.`id` INNER JOIN `stations` AS `dst_station` ON `trains`.`destination` = `dst_station`.`id` INNER JOIN `tickets` ON `trains`.`id` = `tickets`.`train` GROUP BY `tickets`.`train` ORDER BY `id` ASC;

SELECT `trains`.`id` AS `id`, `types`.`name` AS `type`, `src_station`.`name` AS `src_stn`, `dst_station`.`name` AS `dst_stn`, count(`tickets`.`train`) AS `occupied`, `types`.`max_seats` AS `maximum` FROM `trains` INNER JOIN `types` ON `trains`.`type` = `types`.`id` INNER JOIN `stations` AS `src_station` ON `trains`.`source` = `src_station`.`id` INNER JOIN `stations` AS `dst_station` ON `trains`.`destination` = `dst_station`.`id` LEFT OUTER JOIN `tickets` ON `trains`.`id` = `tickets`.`train` GROUP BY `tickets`.`train` ORDER BY `id` ASC;